### ISSUE TITLE
Agregar en el enunciado de TP

### ISSUE THREAD

**Issue by rejurime** [tgc-utn/tgc-utn.github.io#18]
En la entrega 3 agregar que el menú debe ser (o contener) 3d y que ademas debe tener sonido y música.

**Comment by Javier-Rotelli** [comment]
@LeandroJavierLaino este issue se puede considerar hecho no?

**Comment by LeandroJavierLaino** [comment]
@Javier-Rotelli Si recién lo revise estaba como una anotación nada más. Ya lo agregue como parte de la 3er entrega!
