### ISSUE TITLE
Faltan los trabajos anteriores

### ISSUE THREAD

**Issue by rejurime** [tgc-utn/tgc-utn.github.io#4]
En la sección de trabajo la parte histórica no esta migrada http://tgc-utn.github.io/trabajos/
Tiene un cartel de próximamente, no se si aun siguen con la política de publicarlas o no.

**Comment by rejurime** [comment]
Faltan los links de descarga de los proyectos anteriores y darle estilo a los post :stuck_out_tongue_winking_eye:

**Comment by rejurime** [comment]
Ah y faltan los cuatrimestres del 2013 hasta el 2015, alguien tiene los TPs entregados?

**Comment by DNAngeluS** [comment]
Rene, ahi te paso los TPs2014 que son los que tengo yo en esta maquina,
2015 no tengo nada y 2013 los debo tener en la otra pc (los paso cuando
vuelvo a baires).

TPs2014: http://we.tl/hBEBq7Sp1Q

Saludos

---

L

2016-03-10 19:23 GMT-03:00 René Juan Rico Mendoza <notifications@github.com>
:

**Comment by mysery** [comment]
están los de todo el año? (dos cuatrimestres?)
rene ya no esta los estoy agregando yo. ese link es seguro como para
subirlo a la web?

**Comment by rejurime** [comment]
Del 2013 en tgc utn solo estan los del 1c, ya los del segundo no se publicaron mas... ose que si el archivo que mando Lucio estan los del 2014 aun faltarian los del 2c del 2013 y todo 2015. Igual esta bueno tenerlos todos que no se pierdan mas alla de subirlos

**Comment by rejurime** [comment]
Es mas ya son tantos que en algun momento se podrian seleccionar los mejores de cada genero o algo por el estilo zzapis o asado de por medio todos XP

**Comment by mysery** [comment]
Agregar 
2014-2C -> https://drive.google.com/open?id=0B8iAMXTVXrJeQlFFRi1XZHN3Qzg
2015-1C -> https://drive.google.com/open?id=0B8iAMXTVXrJeZVYtZHFMYXlaMTg

**Comment by rejurime** [comment]
No falta 2015 - 2c?

**Comment by mysery** [comment]
si, pero cree otra issue para diferenciar bien.
hay que generar los proyectos para esos.

2016-03-21 19:00 GMT-03:00 René Juan Rico Mendoza <notifications@github.com>
:
