### ISSUE TITLE
Links caidos TP Actual

### ISSUE THREAD

**Issue by rejurime** [tgc-utn/tgc-utn.github.io#6]
En http://tgc-utn.github.io/trabajos/actual/ hay 2 links caidos
[Texturas del juego Ryzom](http://media.ryzom.com/?query=texture%20image%20tile&start=580)
[Texturas de SkyBox](http://www.3delyvisions.com/) (no esta caído pero no creo que sea lo que hay ahora)

**Comment by mysery** [comment]
Aquí otros para skybox (sin verificar demasiado) :P 
http://www.custommapmakers.org/skyboxes.php
las texturas del juego ryzom las encontre aca: http://mirror.fsf.org/ryzom/storage/ pero digamos que buscar una textura es casi imposible, no se a donde apuntaba ese link, tampoco se si sera necesario que se agregue.
