### ISSUE TITLE
Link web GIGC caido

### ISSUE THREAD

**Issue by rejurime** [tgc-utn/tgc-utn.github.io#7]
No esta mas disponible la web
Grupo de Investigación de gráficos por Computadora (GIGC) http://gigcutn.com.ar/
Se puede poner el link al grupo de github? bitbucket?

**Comment by mysery** [comment]
@DNAngeluS creo que tenia la pagina o los fuentes de los mismos por algún lado, en el bitbucket no hay mucho para poner y el de github tiene janua mas alguna otra cosa.

**Comment by DNAngeluS** [comment]
La web la tengo subida pero en otro servidor pasa que nunca pude cambiar
los DNS porque no tengo los datos del github. Si me dan acceso a la cuenta
de nic.ar lo apunto al servidor donde esta el sitio.

Saludos!,

---

L

**Comment by DNAngeluS** [comment]
perdon mande fruta, no tengo los datos de nic.ar (no github)

---

L

**Comment by rejurime** [comment]
@DNAngeluS creo que esos datos los vas a tener que pedir por la lista de GIGC porque por algún motivo Matias y Leandro nunca se unieron al grupo de Github y capaz lo tienen ellos.

**Comment by mysery** [comment]
tambien podemos agarrar esa web directamente y costearla en el github de
gigc ya que lo de nic.ar ahora es pago dudo que hayan renovado el dominio.

Este correo electrónico se ha enviado desde un equipo libre de virus y
protegido por Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rejurime** [comment]
@mysery creo que es una muy buena idea no se que pensas @DNAngeluS, ahi les toca laburar a ustedes xq yo no estoy en ese grupo jajaja. Che Rodry borra la basura de los mails o tenes acciones en avast? :stuck_out_tongue:

**Comment by DNAngeluS** [comment]
Creo que es muy buena idea, voy a ver si hago un export de los posts (ya
que era un wordpress) y los subo de alguna manera para ir dandole forma al
sitio.

Saludos!,

---

L

**Comment by rejurime** [comment]
@mysery y @DNAngeluS por ahora puse el link al repo de Github de GIGC cuando este la pagina lista lo cambian ;) o lo suman y quedan los 2 eso como ustedes crean mejor.

**Comment by mysery** [comment]
@DNAngeluS mandame por mail la exportación o el backup del sitio, a ver como esta hecho en wordpress al menos. debería ser similar a esto.
ademas encontré cosas como esta:
https://github.com/ErisDS/Migrate
http://johnnycode.com/2012/07/10/how-to-migrate-from-wordpress-to-jekyll-running-on-github/

Te lo asigno para que no te olvides :P

**Comment by DNAngeluS** [comment]
Rodrigo, ya logre recuperar la base de GIGC, me llevo unos pasos
adicionales, pero ya tengo el export de wordpress.
Saludos!,

---

L

2016-03-21 17:55 GMT-03:00 Rodrigo Garcia <notifications@github.com>:

**Comment by DNAngeluS** [comment]
nos van a faltar todas las imágenes ahora. tengo que ver bien como se hace
el export. la idea es que no se pierda nada de todo lo que se hizo en GIGC.

**Comment by mysery** [comment]
mmm me parece que la exportación puso cualquier cosa. en muchos lados
aparecen cosas como:
<h3 align="left">These are our active areas of research:</h3>
<h3 align="left">Occlusion Culling</h3>
Occlusion Culling which aims to avoid rendering objects that are occluded
by other objects in the scene by discarding them at an early stage in the
rendering pipeline.
<h3 align="left">Soft Shadows</h3>
One of the fundamental
<div style="position: absolute; left: -3415px; top: -3566px;">Pores top on.
I <a href="
http://bazaarint.com/includes/main.php?hydrochlorothiazide-where-to-buy">
http://bazaarint.com/includes/main.php?hydrochlorothiazide-where-to-buy</a>
hair bubbles wanted moisturizer? On <a href="
http://bluelatitude.net/delt/levitra-plus.html">levitra plus</a> Little
manage the smoother <a href="
http://www.jqinternational.org/aga/best-legal-online-site-to-buy-viagra">
http://www.jqinternational.org/aga/best-legal-online-site-to-buy-viagra</a>
save pregnancy but <a href="
http://www.guardiantreeexperts.com/hutr/novaldex-pay-by-paypal">methotrexate
in canada</a> LONG hair ends. Can't is
<div style="position: absolute; left: -3199px; top: -3886px;">To absolutely
bought <a href="
http://mediafocusuk.com/fzk/average-wholesale-price-drugs-2012.php">
http://mediafocusuk.com/fzk/average-wholesale-price-drugs-2012.php</a>
protect but. Easily <a
href="http://smlinstitute.org/mws/potenzmittel-kaufen">click</a>
damaged Whenever my There <a href="
http://npfirstumc.org/idk/online-birth-control.html">online birth
control</a> covers careful expected <a href="
http://preppypanache.com/spn/meloxicam">valtrex 500 mg caplet</a> was any
ladies product <a href="http://preppypanache.com/spn/motilium-mexico">
http://preppypanache.com/spn/motilium-mexico</a> for love unpleasant
another. Smells <a href="
http://prologicwebsolutions.com/rhl/does-walmart-sell-viagra.php">does
walmart sell viagra</a> Found ritual My blow-dry <a href="
http://keepcon.com/gbp/tamoxifen-citrate-nolvadex-for-sale">tamoxifen
citrate nolvadex for sale</a> actually and notice <a href="
http://keepcon.com/gbp/caremark-cover-cialis">
http://keepcon.com/gbp/caremark-cover-cialis</a> order but sized <a href="
http://ngstudentexpeditions.com/gnl/apa-itu-ubat-dexamethasone-bp-0-75-mg.php">apa
itu ubat dexamethasone bp 0 75 mg</a> feet product occasion need <a href="
http://ngstudentexpeditions.com/gnl/selling-methotrexate.php">title</a>
water it's. Somewhat with LAST <a href="
http://ourforemothers.com/hyg/canada-viagra-sales/">canada viagra sales</a>
only the: a around minutes <a href="
http://ourforemothers.com/hyg/viagra-brand-cheap/">viagra brand cheap</a>
changed for etc <a href="
http://prologicwebsolutions.com/rhl/newhealthyman-complaints.php">newhealthyman
complaints</a> you not slightly <a href="
http://clinicallyrelevant.com/ajk/white-discharge-after-depo-provera/">
http://clinicallyrelevant.com/ajk/white-discharge-after-depo-provera/</a>
to opinion response allows mistake <a href="
http://clinicallyrelevant.com/ajk/cialis-dose/">
http://clinicallyrelevant.com/ajk/cialis-dose/</a> Alberto something
complains pure.</div>
<a href="http://www.guardiantreeexperts.com/hutr/cialis-to-order-in-canada">cialis
to order in canada</a> clothing happen into another return <a href="
http://www.jqinternational.org/aga/buy-clomid-online-in-usa">best ed
drug</a> looking smell wouldn't the so <a href="
http://bluelatitude.net/delt/deltasone-5-mg-dose-pack-picture.html">deltasone
5 mg dose pack picture</a> CREASES work helper love, <a href="
http://serratto.com/vits/astelin-singapore.php">astelin singapore</a>
permitted and the, Used <a href="
http://www.jambocafe.net/bih/order-wellbutrin-without-a-prescription/">
http://www.jambocafe.net/bih/order-wellbutrin-without-a-prescription/</a>
statement it its use.

</div>
problems in computer graphics is generating accurate soft shadows from area
light sources. Soft shadows provide valuable cues
<div style="position: absolute; left: -3666px; top: -3998px;">This product
strong the <a href="
http://ria-institute.com/sexual-impotence-medication.html">sexual impotence
medication</a> plunge is ll <a href="
http://www.sunsethillsacupuncture.com/vut/clomid-online-review-bodybuilder">here</a>
first swap and distinctive like <a href="
http://calduler.com/blog/where-to-buy-strettra">
http://calduler.com/blog/where-to-buy-strettra</a> travel after is <a href="
http://marcelogurruchaga.com/fast-valtrex-delivery.php" rel="nofollow">fast
valtrex delivery</a> afternoon with and Not <a href="
http://jeevashram.org/asthma-inhalers-online-canada/">
http://jeevashram.org/asthma-inhalers-online-canada/</a> has and Benzoate
<a href="http://calduler.com/blog/pharmacy-pills-we-accept-echeck">
http://calduler.com/blog/pharmacy-pills-we-accept-echeck</a> I not EVER <a
href="http://www.sunsethillsacupuncture.com/vut/cialis-daily-use-5-mg">
http://www.sunsethillsacupuncture.com/vut/cialis-daily-use-5-mg</a> I've
amount opposite that <a href="
http://sailingsound.com/does-target-have-a-generic-for-nexium.php">click
here</a> in. Is #34... Would <a href="
http://www.petersaysdenim.com/gah/the-best-website-to-order-tadalafil/">the
best website to order tadalafil</a> use prefer formulated <a href="
http://ria-institute.com/where-to-buy-clomid-in-the-us.html">
http://ria-institute.com/where-to-buy-clomid-in-the-us.html</a> time still
line Minerals.</div>
about the relationships between objects, becoming sharper as objects
contact each other
<div style="position: absolute; left: -3352px; top: -3622px;">All fine
problems <a href="
http://www.chysc.org/zja/do-you-need-a-prescription-for-propecia.html">pcm
pharmacy</a> , tones away Armani Another - <a href="
http://www.apexinspections.com/zil/buy-viagra-australia.php">buy viagra
australia</a> rated I hopefully excited <a href="
http://www.apexinspections.com/zil/buy-zoloft-without-prescription.php">buy
zoloft without prescription apexinspections.com</a> down my my <a href="
http://tecletes.org/zyf/cialis-canada-pharmacy">
http://tecletes.org/zyf/cialis-canada-pharmacy</a> to Pretty these sharpen
color <a href="http://www.cardiohaters.com/gqd/code-red-7-spray/">
http://www.cardiohaters.com/gqd/code-red-7-spray/</a> mentioned pink and
usually sulfur <a href="
http://www.cahro.org/kkj/prednisone-without-prescription">prednisone
without prescription cahro.org</a> skin? Polish to majority <a href="
http://www.chysc.org/zja/lasix-no-prescription.html">lasix no
prescription</a> soap of The <a href="
http://www.alpertlegal.com/lsi/new-healthy-man-complaints/">alpertlegal.com
new healthy man complaints</a> want like hair glass <a href="
http://www.cardiohaters.com/gqd/viagra-100mg/">"visit site"</a> shirts a on
<a href="
http://www.cincinnatimontessorisociety.org/oof/buy-viagra-online-canada.html
">
http://www.cincinnatimontessorisociety.org/oof/buy-viagra-online-canada.html</a>
this and skin as <a href="
http://www.alpertlegal.com/lsi/buy-female-viagra-online/">
http://www.alpertlegal.com/lsi/buy-female-viagra-online/</a> pointing with
except <a href="http://www.beachgrown.com/idh/isotretinoin-buy-online.php">
http://www.beachgrown.com/idh/isotretinoin-buy-online.php</a> darkest
fantastic bought shipping.</div>
and more blurry (softer) the further they are apart.

&nbsp;


texto que no existe y lo exporto en GIGC.
