### ISSUE TITLE
Link unidad 5 caido

### ISSUE THREAD

**Issue by rejurime** [tgc-utn/tgc-utn.github.io#8]
En la unidad 5 http://tgc-utn.github.io/clases/unidad5/
[Applet ángulos de Euler](http://prt.fernuni-hagen.de/lehre/KURSE/PRT001/course_main_sh3d/node11.html)
esta caido

**Comment by mysery** [comment]
Podemos buscar un remplazo, ya que los applets están pasados de moda, del udacity:
Un demo de avión con movimientos de euler: al poner eje y en 90 grados se nota como se produce el gimbal lock
https://assignments-dot-udacity-extras.appspot.com/classes/cs291/demo/unit4/02
También esta este donde se ve bien porque es necesario el uso de quaterniones en las animaciones con rotaciones:
https://assignments-dot-udacity-extras.appspot.com/classes/cs291/demo/unit10/06
(hay que poner sin quaterniones y con hat axis aling con movimientos de 90 hacia delante 90 hacia atras. se ve como se mueve de forma extraña cuando no se usan quaterniones.)
